-- MySQL Script generated by MySQL Workbench
-- Mon Apr 10 17:34:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `library` ;

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`book` ;

CREATE TABLE IF NOT EXISTS `library`.`book` (
  `isbn_book` VARCHAR(45) NOT NULL,
  `book_name` VARCHAR(100) NULL DEFAULT NULL,
  `book_amount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`isbn_book`),
  UNIQUE INDEX `book_isbn_UNIQUE` (`isbn_book` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`borrow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`borrow` ;

CREATE TABLE IF NOT EXISTS `library`.`borrow` (
  `id_borrow` INT NOT NULL AUTO_INCREMENT,
  `borrow_initial_date` DATE NULL,
  `borrow_final_date` DATE NULL,
  `book_isbn_book` VARCHAR(45) NOT NULL,
  `borrow_return` TINYINT NULL,
  `borrow_return_date` DATE NULL,
  PRIMARY KEY (`id_borrow`, `book_isbn_book`),
  UNIQUE INDEX `idborrow_UNIQUE` (`id_borrow` ASC) VISIBLE,
  INDEX `fk_borrow_book_idx` (`book_isbn_book` ASC) VISIBLE,
  CONSTRAINT `fk_borrow_book`
    FOREIGN KEY (`book_isbn_book`)
    REFERENCES `library`.`book` (`isbn_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `library`.`book`
-- -----------------------------------------------------
START TRANSACTION;
USE `library`;
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('32D13G2', 'Lord of the Rings', 10);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('A4D6J2F', 'To Kill a Mockingbird', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('A9K2J6F', 'The Count of Monte Cristo', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('B3K5J9F', 'Heart of Darkness', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('B6G9F3K', '1984', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('C3F6G9J', 'The Great Gatsby', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('C9J6K2F', 'Moby-Dick', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('D1K9J7F', 'The Odyssey', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('D5H3K9J', 'The Catcher in the Rye', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('E1F9G7H', 'Animal Farm', 9);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('E6J2K9F', 'Hamlet', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('F9K1J2H', 'Macbeth', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('G2J9K6F', 'The Canterbury Tales', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('G9K2J6F', 'Brave New World', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('H3K5J1F', 'The Hobbit', 12);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('H6K5J2F', 'The Divine Comedy', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('J2F6G9H', 'The Hunger Games', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('J9K2F6H', 'Don Quixote', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('K4J9F2H', 'Fahrenheit 451', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('K5J3H9F', 'Robinson Crusoe', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L2K9J6F', 'The Iliad', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('M1F7G3K', 'The Lord of the Flies', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('M6J1K9F', 'The Aeneid', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('N2K5J9F', 'Paradise Lost', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('N7H4K2J', 'Pride and Prejudice', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('P6J5K9F', 'One Hundred Years of Solitude', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('P9J6K3F', 'The Canterbury Tales', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Q2K6J9F', 'Crime and Punishment', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Q5K2J9F', 'Gulliver\'s Travels', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('R5J1K9F', 'The Picture of Dorian Gray', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('R9J3K6F', 'Jane Eyre', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('S2K5J9F', 'Tess of the d\'Urbervilles', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('S9K3J7F', 'Wuthering Heights', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('T1F9K7J', 'The Brothers Karamazov', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('T5J2K9F', 'The War of the Worlds', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('V1K6J3F', 'The Time Machine', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('V7H9K1F', 'Anna Karenina', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('W3J5K2F', 'The Adventures of Huckleberry Finn', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('W6J9K2F', 'Dracula', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('X2J5K9F', 'The Strange Case of Dr Jekyll and Mr Hyde', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('X9K1J5F', 'The Grapes of Wrath', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Y2J6K9F', 'Frankenstein', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Y6K3J9F', 'The Hound of the Baskervilles', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Z2J9K5F', 'The Adventures of Sherlock Holmes', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Z5K9J1F', 'The Scarlet Letter', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('B2J5K8F', 'The Kite Runner', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('C4K2J8F', 'The Book Thief', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('D6J2K8F', 'The Chronicles of Narnia', 10);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('E9K1J7F', 'The Hitchhiker\'s Guide to the Galaxy', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('F5J1K8F', 'The Giver', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('G3K8J1F', 'The Handmaid\'s Tale', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('H9K7J2F', 'The Secret History', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('J1K5F9H', 'The Name of the Wind', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('K6J2F7H', 'The Girl with the Dragon Tattoo', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L3K9J1F', 'The Wind-Up Bird Chronicle', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('M8J2K4F', 'The Shadow of the Wind', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('N3J9K6F', 'The Book of Lost Things', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('P2K8J5F', 'The Power of One', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Q7K1J4F', 'The Poisonwood Bible', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('R1K9J5F', 'The Road', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('S8K2J1F', 'The Nightingale', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('T3J7K5F', 'The Martian', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('V2K8J6F', 'The Fault in Our Stars', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('X1J5K8F', 'The Hunger Artist', 2);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('A1F6K8J', 'The Silent Patient', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('B2J6K9F', 'The Testaments', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('C4K3J7F', 'The Immortalists', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('D6J3K9F', 'Little Fires Everywhere', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('E9K2J8F', 'Educated', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('F5J2K8F', 'A Little Life', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('G3K9J2F', 'Normal People', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('H9K8J1F', 'The Water Dancer', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('J1K6F8H', 'The Overstory', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('K6J3F9H', 'The Nickel Boys', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L3K8J2F', 'The Immortal Life of Henrietta Lacks', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('M8J3K5F', 'The Dutch House', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('N3J8K6F', 'The Glass Hotel', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('P2K7J5F', 'The Vanishing Half', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Q7K2J4F', 'An American Marriage', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('R1K8J5F', 'The Mothers', 2);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('S8K3J1F', 'Red at the Bone', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('T3J6K5F', 'The City We Became', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('V2K7J6F', 'The Great Believers', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('X1J6K9F', 'The Night Watchman', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('A3K7J5F', 'The Silent Wife', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('B4J6K8F', 'The Song of Achilles', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('C5J9K2F', 'The Midnight Library', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('D8K2J7F', 'The House in the Cerulean Sea', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('E2J6K9F', 'The Seven Husbands of Evelyn Hugo', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('F7K3J9F', 'The Starless Sea', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('G8K2J6F', 'The Invisible Life of Addie LaRue', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('H5K9J1F', 'The Vanished Birds', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('J2K6F9H', 'The Heart\'s Invisible Furies', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L1K7J9F', 'The Traveling Cat Chronicles', 2);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('N9K2J4F', 'The Glass Castle', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('S6K2J8F', 'The Rosie Project', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('T2J7K5F', 'The Book of Longings', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('V8K3J2F', 'The Death of Vivek Oji', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('I3K35J2', 'The Leavers', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('K2J3HD8', 'Diary of a Wimpy Kid', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('3JF8U3W', 'The Winter of the Witch', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L2K4J8A', 'Sky in the Deep', 12);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Y1H2A2D', 'Dear Mrs Bird', 17);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('P3S1D4X', 'My Heart and Other Black Holes', 10);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('N2Z3B2F', 'The Blue Sword', 20);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('J1D2H31', 'Dread Nation', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L3K3H1J', 'The Hazel Wood', 2);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('N39S1L2', 'Sleeping Beauties', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('W2P30A2', 'Wilder Girls', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('O3K1J3H', 'Slade House', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('K2O23J2', 'Diary of a Madman', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L2E2D21', 'Stories', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LWFJ32S', 'Invisible Man', 1);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('JO232EQ', 'The Decameron', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L12EKE3', 'Children of Gebelawi', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L1EDDDK', 'Ulysses', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('PQD1315', 'Leaves of Grass', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L2I3RFL', 'The Book Of Job', 10);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('I093DKL', 'Things Fall Apart', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('1023FWD', 'The Epic Of Gilgamesh', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LDI24EE', 'The Red and the Black', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('4T3DSWS', 'The Sound and the Fury', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L12923S', 'Gypsy Ballads', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LRE903W', 'Metamorphoses', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('WLSCI93', 'King Lear', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('129EDIO', 'Love in the Time of Cholera', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LD91EDF', 'The Sound of the Mountain', 9);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LS8C12D', 'Bostan', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L2912FF', 'Jacques the Fatalist', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('1209DOL', 'The Devil to Pay in the Backlands', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('1932RKQ', 'The Possessed', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('R902OKL', 'Nineteen Eighty-Four', 12);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('2K3FUI9', 'Mrs Dalloway', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('3290OFM', 'Mahabharata', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QWLWFJ9', 'Hunger', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QWLF91E', 'The Man Without Qualities', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('214EW21', 'Memoirs of Hadrian', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('WELW1E4', 'The Golden Notebook', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LO129DQ', 'Medea', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('KMF9LKW', 'Sentimental Education', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('09I329I', 'To the Lighthouse', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('21EO1DS', 'Le PÃƒÂ¨re Goriot', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('SU1I12D', 'The Death of Ivan Ilyich', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('SLD1432', 'Berlin Alexanderplatz', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('1LOE81W', 'Buddenbrooks', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('MDIFJIE', 'The Trial', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('OKQ8732', 'War and Peace', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('WQKJD28', 'Oedipus the King', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LQO12WD', 'Faust', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LOQP232', 'The recognition of Shakuntala', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('WE923FW', 'Pippi Longstocking', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('KIS30WE', 'Confessions of Zeno', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('4QDQ484', 'The Magic Mountain', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LOSD412', 'Fairy tales', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('4A1FEQ1', 'A Doll\'s House', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('UH3F91D', 'Great Expectations', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L9SQI3E', 'The Unnamable, the trilogy', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('O219E18', 'Essays', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('12E98DJ', 'The Idiot', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('12E98UD', 'The Tale of Genji', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('UI12DWQ', 'One Thousand and One Nights', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('19JEIDW', 'History', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('12D9IWJ', 'Midnight\'s Children', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QWD82ED', 'Absalom, Absalom!', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('KSOD914', 'NjÃƒÂ¡l\'s Saga', 10);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Q5454SD', 'The Life And Opinions of Tristram Shandy', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('542R324', 'In Search of Lost Time', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('TISJ123', 'Dead Souls', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('TIST12E', 'Nostromo', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('BUWEW13', 'The Tin Drum', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L1ND02S', 'Lolita', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L1O9EOD', 'The Castle', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('IHEIE2W', 'Season of Migration to the North', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('KPO201D', 'Independent People', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('19IDDSQ', 'Moby Dick', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L12IODQ', 'Middlemarch', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('O18MDQE', 'Journey to the End of the Night', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('I92IEQW', 'Sons and Lovers', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QWDIUJE', 'Ramayana', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('KQI93R2', 'The Book of Disquiet', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QWE83KW', 'Madame Bovary', 2);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('982EJID', 'Ficciones', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('87EUEWR', 'Zorba the Greek', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QLE0EWF', 'The Stranger', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('432RFFR', 'Blindness', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('412E43E', 'The Old Man and the Sea', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('32I8FWE', 'Gargantua and Pantagruel', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('85UJKWL', 'Pedro PÃƒÂ¡ramo', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('23QQEFF', 'Beloved', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('542EFEW', 'Othello', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('54WQE12', 'The Masnavi', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QWKO29D', 'Unearthed Dissertation on the History of the Dwarfs', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QLP122E', 'Heart of Darkvision', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('12KE9LQ', 'Precious Pies: The Cuisine of the Swamp', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Q1O2EKW', 'Compulsory Rudiments of the Giant Lexicon', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QKL202D', 'Quickening Fare: Riverside Feasts', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('KOSQ2EW', 'How to Cast Friends and Polymorph People', 2);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QKEL9W4', 'Appetizing Menus: Secrets of the Hearth Revealed', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('8920WRE', 'Evocative Paths of the Canyon: Castles and Cul de Sacs', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LDSO231', 'Llothlita', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QWE32EW', 'Loathsome Dwellers of the Tooth', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LP120E9', 'Lectures on the Creatures of Chaos: A Natural Philosophy', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('WQDK12E', 'Man\'s Prize (A book on paintings)', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LP1203E', 'A Thousand Splendid Sunbursts', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QEM2132', 'Lovely Travels in the Coastline', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QL203DW', 'Ultimate Chronicles', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('MK12032', 'The Empirical Feats of the Champion', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L21E0OQ', 'Kobold Jokes: A joke book, written in Draconic', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('MDQKO12', 'Amazing Crossings of the Great Desert: Troubled Trails of a Tract Most Terrible', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L2309EW', 'The Next Hunt - Volume I: Wyverns', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QIWE9WE', 'The Dream Prize (A comedy stage play)', 2);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('5QWE2D2', 'Fine Tales of the Knight: A True Heir', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('WQLO251', 'War of the Wurms', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QK9245Q', 'Seminars on the Beings of Blood: Magnificent Creatures', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LOP1209', 'The Moonsea Chronicles', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LP12DQE', 'Principals Foresights of Deciphering Scripts', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L012EQ1', 'Distant Domains of the Cave', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('0OQE2E1', 'Four Awakening (A songbook of lullabies and children\'s songs)', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LP12QEW', 'Distant Lands of the Grey Mountains: Tales of a Rover', 12);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('96WEEW4', 'Black Memory (Instructive moral stories for young lovers)', 17);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Q5EQW24', 'The Gallant Conundrums of the Sea Captain: A Fate Forfeit', 10);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('452EWQW', 'White Dawn', 20);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LO1245W', 'Memorable Sunsets of the Sea: A Voyage Remembered', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('8OSI224', 'Superlative Mysteries of the Humans', 2);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L1DSAF2', 'Holy Demands of the Humans', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LPA23DW', 'The Great Chronicles of the Duellist', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('SKD1012', 'The Unearthed Visions of the Bard: For Which He Was Burnt', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('JDK12E9', 'Thesis on the Children of the Tomb', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('COD124E', 'Dusty Domains of the Black Mountains: A Walkabout in the Wild', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('BFI1DSQ', 'The Shadow of the Crescent', 1);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('BTF1DAS', 'Blue Horizon\'s Edge', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('VL12DAF', 'The Crystal Labyrinth', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('IEW981W', 'Echoes in the Abyss', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('129EIQW', 'Midnight\'s Symphony', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('29IKQWQ', 'The Garden of Ghosts', 10);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QWE9E3W', 'Crimson Dawn\'s Embrace', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QWKE23E', 'The Kingdom of Ashes', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QKUD232', 'Phoenix of the Black Sun', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('KQ09923', 'The Silence of the Stars', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('988WDSQ', 'The Lost Kingdom of Atlantis', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('56WQDSS', 'The Witching Hour\'s Spell', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('154QSDS', 'The Secret Garden of Dreams', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('REI4SAS', 'The Enchanted Forest\'s Tale', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('56VSQAC', 'The Last Sunset of the Samurai', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('8YWSA92', 'The Darkening Sky\'s Promise', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('I9AIJDS', 'The Wind\'s Whispers', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('89ISAMK', 'The Hidden Path of the Druids', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('IA8DISA', 'The Blade of the Samurai', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('9IKASDQ', 'The Tears of the Phoenix', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('E129IKS', 'The Island of the Serpents', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('IOOIJWD', 'The Forbidden City\'s Secret', 2);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('219IQES', 'The Heart of the Dragon', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('12EOQWE', 'The Haunting of Ravenwood Manor', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('109KDSA', 'The Curse of the Mummy\'s Tomb', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('W9KOAD2', 'The Ghosts of Greyhaven', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('19JIOKA', 'The Vampire\'s Masquerade', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('09OWQAS', 'The Witches Moon', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('891HUKA', 'The Secrets of the Sphinx', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('KOSAD3S', 'The Dragon\'s Lair', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('09JOIKA', 'The Enigma of the Illuminati', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LP210DQ', 'The Dark Forest\'s Mystery', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('LOP12ED', 'The Shadow Hunter\'s Quest', 2);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('S9O21DS', 'The Lost World of Dinosaurs', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('1KOAD12', 'The Secret Chamber of King Tut', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('0OASDSD', 'The Wonders of the Amazon', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('89SF23W', 'The Search for the Holy Grail', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('1ISDX23', 'The Quest for the Fountain of Youth', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('89HJISQ', 'The Gates of Valhalla', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('198JIQD', 'The Songs of the Siren', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('OK01ED4', 'The Dark Side of the Moon', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('9DQW23E', 'The Ghosts of Whitby', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('198UJIS', 'The Secret Garden of the Faeries', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('8HUIDAS', 'The Island of Dr. Moreau', 2);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('89IJDAS', 'The Cursed Sword of Excalibur', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('198JDIS', 'The Tower of London\'s Mystery', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('9812JID', 'The Witching Hour\'s Curse', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('45D13RF', 'The Island of Lost Souls', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('55718DH', 'The Legend of Sleepy Hollow', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('H8235AD', 'The Ghosts of Versailles', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('56QWD4E', 'The Quest for the Crystal Skull', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('54EWFOI', 'The Haunting of Hill House', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('57SDF2F', 'The Secret Garden of the Gods', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('98JIASD', 'The Curse of the Werewolf', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('92DSWQO', 'The Forbidden Island\'s Secret', 2);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('IHQW12E', 'The Enigma of the Bermuda Triangle', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('651SDD2', 'The Witching Hour\'s Legacy', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('98HIUDS', 'The Dark Crystal\'s Secret', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('SAD212E', 'The Island of the Dead', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('36DQD24', 'The Ghosts of Gettysburg', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('1OISAD3', 'The Secret Garden of the Stars', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('1OIOJDQ', 'The Curse of the Black Pearl', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('KSOD1DA', 'The Shadow of the Sphinx', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('562QWD3', 'The Enigma of the Stonehenge', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('398DJSD', 'The Witching Hour\'s Legacy', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('239DJIQ', 'The Island of the Damned', 2);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('19AJIQD', 'The Ghosts of St. Petersburg', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('AOPQDAS', 'The Secret Garden of the Moon', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('QWOI1Q2', 'The Curse of the Aztec Gold', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('190IDAS', 'The Shadow of the Tower', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('89WEV23SD', 'Show me the way', 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `library`.`borrow`
-- -----------------------------------------------------
START TRANSACTION;
USE `library`;
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (1, '2023-04-06', '2023-04-14', 'L2K9J6F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (2, '2023-04-08', '2023-04-15', 'N2K5J9F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (3, '2023-04-09', '2023-04-16', 'H3K5J1F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (4, '2023-04-10', '2023-04-17', 'M1F7G3K', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (5, '2023-04-11', '2023-04-18', 'S2K5J9F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (6, '2023-04-12', '2023-04-19', 'J9K2F6H', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (7, '2023-04-13', '2023-04-20', 'Q2K6J9F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (8, '2023-04-14', '2023-04-21', 'V1K6J3F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (9, '2023-04-15', '2023-04-22', 'Q5K2J9F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (10, '2023-04-16', '2023-04-23', 'B6G9F3K', 0, NULL);

COMMIT;

USE `library`;

DELIMITER $$

USE `library`$$
DROP TRIGGER IF EXISTS `library`.`check_book_amount` $$
USE `library`$$
CREATE DEFINER = CURRENT_USER TRIGGER `check_book_amount` BEFORE INSERT ON `borrow` FOR EACH ROW
BEGIN
	DECLARE book_amount INT;
    SELECT book_amount INTO book_amount FROM book WHERE isbn_book = NEW.book_isbn_book;
    IF book_amount < 1 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'The book amount is not enough to borrow';
    END IF;
END$$


USE `library`$$
DROP TRIGGER IF EXISTS `library`.`decrease_book_amount` $$
USE `library`$$
CREATE DEFINER = CURRENT_USER TRIGGER `decrease_book_amount` AFTER INSERT ON `borrow` FOR EACH ROW
BEGIN
	IF NEW.borrow_return = 0 THEN
		 UPDATE book SET book_amount = book_amount - 1 WHERE isbn_book = NEW.book_isbn_book;
	END IF;
END$$


USE `library`$$
DROP TRIGGER IF EXISTS `library`.`increase_book_amount` $$
USE `library`$$
CREATE DEFINER = CURRENT_USER TRIGGER `increase_book_amount` AFTER UPDATE ON `borrow` FOR EACH ROW
BEGIN
	 IF NEW.borrow_return = 1 AND NEW.borrow_return_date IS NOT NULL THEN
        UPDATE book SET book_amount = book_amount + 1 WHERE isbn_book = NEW.book_isbn_book;
    END IF;
END$$


DELIMITER ;
