-- MySQL Script generated by MySQL Workbench
-- Thu Apr  6 15:59:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `library` ;

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`book` ;

CREATE TABLE IF NOT EXISTS `library`.`book` (
  `isbn_book` VARCHAR(45) NOT NULL,
  `book_name` VARCHAR(45) NULL DEFAULT NULL,
  `book_amount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`isbn_book`),
  UNIQUE INDEX `book_isbn_UNIQUE` (`isbn_book` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`borrow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`borrow` ;

CREATE TABLE IF NOT EXISTS `library`.`borrow` (
  `id_borrow` INT NOT NULL AUTO_INCREMENT,
  `borrow_initial_date` DATE NULL,
  `borrow_final_date` DATE NULL,
  `book_isbn_book` VARCHAR(45) NOT NULL,
  `borrow_return` TINYINT NULL,
  `borrow_return_date` DATE NULL,
  PRIMARY KEY (`id_borrow`, `book_isbn_book`),
  UNIQUE INDEX `idborrow_UNIQUE` (`id_borrow` ASC) VISIBLE,
  INDEX `fk_borrow_book_idx` (`book_isbn_book` ASC) VISIBLE,
  CONSTRAINT `fk_borrow_book`
    FOREIGN KEY (`book_isbn_book`)
    REFERENCES `library`.`book` (`isbn_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `library`.`book`
-- -----------------------------------------------------
START TRANSACTION;
USE `library`;
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('isbn_book', 'book_name', book_amount);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('32D13G2', 'Lord of the Rings', 10);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('A4D6J2F', 'To Kill a Mockingbird', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('A9K2J6F', 'The Count of Monte Cristo', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('B3K5J9F', 'Heart of Darkness', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('B6G9F3K', '1984', 8);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('C3F6G9J', 'The Great Gatsby', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('C9J6K2F', 'Moby-Dick', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('D1K9J7F', 'The Odyssey', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('D5H3K9J', 'The Catcher in the Rye', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('E1F9G7H', 'Animal Farm', 9);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('E6J2K9F', 'Hamlet', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('F9K1J2H', 'Macbeth', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('G2J9K6F', 'The Canterbury Tales', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('G9K2J6F', 'Brave New World', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('H3K5J1F', 'The Hobbit', 12);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('H6K5J2F', 'The Divine Comedy', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('J2F6G9H', 'The Hunger Games', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('J9K2F6H', 'Don Quixote', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('K4J9F2H', 'Fahrenheit 451', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('K5J3H9F', 'Robinson Crusoe', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('L2K9J6F', 'The Iliad', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('M1F7G3K', 'The Lord of the Flies', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('M6J1K9F', 'The Aeneid', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('N2K5J9F', 'Paradise Lost', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('N7H4K2J', 'Pride and Prejudice', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('P6J5K9F', 'One Hundred Years of Solitude', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('P9J6K3F', 'The Canterbury Tales', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Q2K6J9F', 'Crime and Punishment', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Q5K2J9F', 'Gulliver\'s Travels', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('R5J1K9F', 'The Picture of Dorian Gray', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('R9J3K6F', 'Jane Eyre', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('S2K5J9F', 'Tess of the d\'Urbervilles', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('S9K3J7F', 'Wuthering Heights', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('T1F9K7J', 'The Brothers Karamazov', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('T5J2K9F', 'The War of the Worlds', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('V1K6J3F', 'The Time Machine', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('V7H9K1F', 'Anna Karenina', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('W3J5K2F', 'The Adventures of Huckleberry Finn', 4);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('W6J9K2F', 'Dracula', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('X2J5K9F', 'The Strange Case of Dr Jekyll and Mr Hyde', 3);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('X9K1J5F', 'The Grapes of Wrath', 6);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Y2J6K9F', 'Frankenstein', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Y6K3J9F', 'The Hound of the Baskervilles', 7);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Z2J9K5F', 'The Adventures of Sherlock Holmes', 5);
INSERT INTO `library`.`book` (`isbn_book`, `book_name`, `book_amount`) VALUES ('Z5K9J1F', 'The Scarlet Letter', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `library`.`borrow`
-- -----------------------------------------------------
START TRANSACTION;
USE `library`;
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (1, '2023-04-06', '2023-04-14', 'L2K9J6F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (2, '2023-04-08', '2023-04-15', 'N2K5J9F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (3, '2023-04-09', '2023-04-16', 'H3K5J1F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (4, '2023-04-10', '2023-04-17', 'M1F7G3K', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (5, '2023-04-11', '2023-04-18', 'S2K5J9F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (6, '2023-04-12', '2023-04-19', 'J9K2F6H', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (7, '2023-04-13', '2023-04-20', 'Q2K6J9F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (8, '2023-04-14', '2023-04-21', 'V1K6J3F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (9, '2023-04-15', '2023-04-22', 'Q5K2J9F', 0, NULL);
INSERT INTO `library`.`borrow` (`id_borrow`, `borrow_initial_date`, `borrow_final_date`, `book_isbn_book`, `borrow_return`, `borrow_return_date`) VALUES (10, '2023-04-16', '2023-04-23', 'B6G9F3K', 0, NULL);

COMMIT;

USE `library`;

DELIMITER $$

USE `library`$$
DROP TRIGGER IF EXISTS `library`.`decrease_book_amount` $$
USE `library`$$
CREATE DEFINER = CURRENT_USER TRIGGER `decrease_book_amount` AFTER INSERT ON `borrow` FOR EACH ROW
BEGIN
	IF NEW.borrow_return = 0 THEN
		 UPDATE book SET book_amount = book_amount - 1 WHERE isbn_book = NEW.book_isbn_book;
	END IF;
END$$


USE `library`$$
DROP TRIGGER IF EXISTS `library`.`increase_book_amount` $$
USE `library`$$
CREATE DEFINER = CURRENT_USER TRIGGER `increase_book_amount` AFTER UPDATE ON `borrow` FOR EACH ROW
BEGIN
	 IF NEW.borrow_return = 1 AND NEW.borrow_return_date IS NOT NULL THEN
        UPDATE book SET book_amount = book_amount + 1 WHERE isbn_book = NEW.book_isbn_book;
    END IF;
END$$


DELIMITER ;
